//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceByTour
    {
        public int ID { get; set; }
        public int ServiceID { get; set; }
        public Nullable<bool> IsControl { get; set; }
    }
}
